// ─── Fleet Maintenance Mock Data ──────────────────────────────

export const FLEET_VEHICLES = [
  { id: 'V001', name: 'Tata Prima 4028.S',   registration: 'KA-01-AB-1234', odometer: 48200, type: 'Heavy Truck'  },
  { id: 'V002', name: 'Ashok Leyland 2518',  registration: 'KA-02-CD-5678', odometer: 72100, type: 'Medium Truck' },
  { id: 'V003', name: 'Eicher Pro 6031',      registration: 'MH-03-EF-9012', odometer: 31500, type: 'Light Truck'  },
  { id: 'V004', name: 'Mahindra Blazo X 35', registration: 'DL-04-GH-3456', odometer: 95400, type: 'Heavy Truck'  },
  { id: 'V005', name: 'Tata LPT 1613',        registration: 'TN-05-IJ-7890', odometer: 12300, type: 'Medium Truck' },
  { id: 'V006', name: 'Volvo FH 500',         registration: 'GJ-06-KL-2345', odometer: 58700, type: 'Heavy Truck'  },
  { id: 'V008', name: 'Eicher Pro 3015',      registration: 'UP-08-OP-0123', odometer: 27800, type: 'Light Truck'  },
];

export const TECHNICIANS = [
  'Rajesh Kumar', 'Sunil Patil', 'Anil Desai', 'Mohan Rao',
  'Vikram Singh', 'Deepak Joshi', 'Sanjay Mehta',
];

export const MAINTENANCE_TYPES = [
  'Oil Change & Filter', 'Brake System Service', 'Tyre Replacement',
  'Engine Overhaul', 'Transmission Repair', 'Electrical System',
  'Suspension Repair', 'AC System Service', 'Coolant System Flush',
  'Annual Safety Inspection', 'Body & Paint', 'Fuel System Service',
];

export const SERVICE_CATEGORIES = [
  'Routine Service', 'Preventive', 'Repair', 'Major Repair', 'Inspection', 'Emergency',
];

export const MAINTENANCE_RECORDS = [
  {
    id: 'MNT-2024-001', vehicleId: 'V003', vehicle: 'Eicher Pro 6031',
    registration: 'MH-03-EF-9012', type: 'Engine Overhaul', category: 'Major Repair',
    technician: 'Rajesh Kumar', priority: 'critical',
    startDate: '2024-12-10', expectedCompletion: '2024-12-14', completionDate: null,
    cost: 48500, actualCost: null, status: 'in_progress',
    odometer: 31500,
    issueDescription: 'Engine knocking noise, oil pressure drop detected during routine check.',
    partsReplaced: ['Piston Rings', 'Crankshaft Bearings', 'Oil Pump'],
    notes: 'Requires full engine teardown. Parts ordered from OEM supplier.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-09 14:00', done: true  },
      { event: 'Inspection Started', time: '2024-12-10 09:00', done: true  },
      { event: 'Repair Started',     time: '2024-12-10 11:30', done: true  },
      { event: 'Parts Ordered',      time: '2024-12-11 08:00', done: true  },
      { event: 'Repair Completed',   time: null,               done: false },
      { event: 'Quality Check',      time: null,               done: false },
      { event: 'Vehicle Available',  time: null,               done: false },
    ],
  },
  {
    id: 'MNT-2024-002', vehicleId: 'V001', vehicle: 'Tata Prima 4028.S',
    registration: 'KA-01-AB-1234', type: 'Brake System Service', category: 'Preventive',
    technician: 'Sunil Patil', priority: 'high',
    startDate: '2024-12-15', expectedCompletion: '2024-12-16', completionDate: null,
    cost: 12000, actualCost: null, status: 'scheduled',
    odometer: 48200,
    issueDescription: 'Scheduled brake pad replacement and brake fluid flush at 50,000 km interval.',
    partsReplaced: ['Brake Pads (Front)', 'Brake Pads (Rear)', 'Brake Fluid'],
    notes: 'Vehicle to be brought in at 08:00 AM.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-13 10:00', done: true  },
      { event: 'Inspection Started', time: null,               done: false },
      { event: 'Repair Started',     time: null,               done: false },
      { event: 'Parts Ordered',      time: null,               done: false },
      { event: 'Repair Completed',   time: null,               done: false },
      { event: 'Quality Check',      time: null,               done: false },
      { event: 'Vehicle Available',  time: null,               done: false },
    ],
  },
  {
    id: 'MNT-2024-003', vehicleId: 'V004', vehicle: 'Mahindra Blazo X 35',
    registration: 'DL-04-GH-3456', type: 'Oil Change & Filter', category: 'Routine Service',
    technician: 'Anil Desai', priority: 'low',
    startDate: '2024-12-08', expectedCompletion: '2024-12-08', completionDate: '2024-12-08',
    cost: 3200, actualCost: 3200, status: 'completed',
    odometer: 95400,
    issueDescription: 'Routine 10,000 km oil change and filter replacement.',
    partsReplaced: ['Engine Oil (15L)', 'Oil Filter', 'Air Filter'],
    notes: 'Next service due at 105,400 km.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-07 16:00', done: true },
      { event: 'Inspection Started', time: '2024-12-08 08:30', done: true },
      { event: 'Repair Started',     time: '2024-12-08 09:00', done: true },
      { event: 'Parts Ordered',      time: '2024-12-08 09:00', done: true },
      { event: 'Repair Completed',   time: '2024-12-08 11:00', done: true },
      { event: 'Quality Check',      time: '2024-12-08 11:30', done: true },
      { event: 'Vehicle Available',  time: '2024-12-08 12:00', done: true },
    ],
  },
  {
    id: 'MNT-2024-004', vehicleId: 'V005', vehicle: 'Tata LPT 1613',
    registration: 'TN-05-IJ-7890', type: 'Tyre Replacement', category: 'Repair',
    technician: 'Mohan Rao', priority: 'medium',
    startDate: '2024-12-12', expectedCompletion: '2024-12-12', completionDate: '2024-12-12',
    cost: 28000, actualCost: 28000, status: 'completed',
    odometer: 12300,
    issueDescription: 'All 6 tyres worn beyond safe tread depth. Replacement required.',
    partsReplaced: ['Tyres x6 (10.00R20)', 'Valve Stems x6'],
    notes: 'Used MRF Meteor tyres as per fleet standard.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-11 11:00', done: true },
      { event: 'Inspection Started', time: '2024-12-12 08:00', done: true },
      { event: 'Repair Started',     time: '2024-12-12 08:30', done: true },
      { event: 'Parts Ordered',      time: '2024-12-12 08:30', done: true },
      { event: 'Repair Completed',   time: '2024-12-12 14:00', done: true },
      { event: 'Quality Check',      time: '2024-12-12 14:30', done: true },
      { event: 'Vehicle Available',  time: '2024-12-12 15:00', done: true },
    ],
  },
  {
    id: 'MNT-2024-005', vehicleId: 'V006', vehicle: 'Volvo FH 500',
    registration: 'GJ-06-KL-2345', type: 'Transmission Repair', category: 'Major Repair',
    technician: 'Rajesh Kumar', priority: 'critical',
    startDate: '2024-12-05', expectedCompletion: '2024-12-10', completionDate: null,
    cost: 95000, actualCost: null, status: 'overdue',
    odometer: 58700,
    issueDescription: 'Gear slipping in 4th and 5th gear. Transmission fluid leak detected.',
    partsReplaced: ['Transmission Fluid', 'Gear Synchronizers', 'Transmission Seal Kit'],
    notes: 'Awaiting specialist technician from Volvo service center.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-04 09:00', done: true  },
      { event: 'Inspection Started', time: '2024-12-05 08:00', done: true  },
      { event: 'Repair Started',     time: '2024-12-05 10:00', done: true  },
      { event: 'Parts Ordered',      time: '2024-12-06 09:00', done: true  },
      { event: 'Repair Completed',   time: null,               done: false },
      { event: 'Quality Check',      time: null,               done: false },
      { event: 'Vehicle Available',  time: null,               done: false },
    ],
  },
  {
    id: 'MNT-2024-006', vehicleId: 'V008', vehicle: 'Eicher Pro 3015',
    registration: 'UP-08-OP-0123', type: 'AC System Service', category: 'Preventive',
    technician: 'Sunil Patil', priority: 'low',
    startDate: '2024-12-16', expectedCompletion: '2024-12-16', completionDate: null,
    cost: 5500, actualCost: null, status: 'scheduled',
    odometer: 27800,
    issueDescription: 'AC not cooling effectively. Gas recharge and compressor check required.',
    partsReplaced: ['AC Refrigerant Gas', 'Cabin Air Filter'],
    notes: 'Driver reported AC issue on last trip.',
    timeline: [
      { event: 'Scheduled',          time: '2024-12-14 15:00', done: true  },
      { event: 'Inspection Started', time: null,               done: false },
      { event: 'Repair Started',     time: null,               done: false },
      { event: 'Parts Ordered',      time: null,               done: false },
      { event: 'Repair Completed',   time: null,               done: false },
      { event: 'Quality Check',      time: null,               done: false },
      { event: 'Vehicle Available',  time: null,               done: false },
    ],
  },
  {
    id: 'MNT-2024-007', vehicleId: 'V002', vehicle: 'Ashok Leyland 2518',
    registration: 'KA-02-CD-5678', type: 'Electrical System', category: 'Repair',
    technician: 'Anil Desai', priority: 'medium',
    startDate: '2024-12-01', expectedCompletion: '2024-12-03', completionDate: '2024-12-03',
    cost: 8700, actualCost: 9200, status: 'completed',
    odometer: 72100,
    issueDescription: 'Alternator failure causing battery drain. Dashboard warning lights active.',
    partsReplaced: ['Alternator', 'Drive Belt', 'Battery Terminal Connectors'],
    notes: 'Actual cost slightly higher due to additional wiring harness repair.',
    timeline: [
      { event: 'Scheduled',          time: '2024-11-30 17:00', done: true },
      { event: 'Inspection Started', time: '2024-12-01 09:00', done: true },
      { event: 'Repair Started',     time: '2024-12-01 10:30', done: true },
      { event: 'Parts Ordered',      time: '2024-12-01 11:00', done: true },
      { event: 'Repair Completed',   time: '2024-12-03 15:00', done: true },
      { event: 'Quality Check',      time: '2024-12-03 15:30', done: true },
      { event: 'Vehicle Available',  time: '2024-12-03 16:00', done: true },
    ],
  },
  {
    id: 'MNT-2024-008', vehicleId: 'V001', vehicle: 'Tata Prima 4028.S',
    registration: 'KA-01-AB-1234', type: 'Suspension Repair', category: 'Repair',
    technician: 'Mohan Rao', priority: 'high',
    startDate: '2024-11-20', expectedCompletion: '2024-11-22', completionDate: '2024-11-22',
    cost: 22000, actualCost: 22000, status: 'completed',
    odometer: 46800,
    issueDescription: 'Front leaf spring broken. Vehicle pulling to one side.',
    partsReplaced: ['Front Leaf Spring Assembly', 'U-Bolts', 'Shock Absorbers (Front)'],
    notes: 'Completed on schedule.',
    timeline: [
      { event: 'Scheduled',          time: '2024-11-19 14:00', done: true },
      { event: 'Inspection Started', time: '2024-11-20 08:00', done: true },
      { event: 'Repair Started',     time: '2024-11-20 09:30', done: true },
      { event: 'Parts Ordered',      time: '2024-11-20 10:00', done: true },
      { event: 'Repair Completed',   time: '2024-11-22 14:00', done: true },
      { event: 'Quality Check',      time: '2024-11-22 14:30', done: true },
      { event: 'Vehicle Available',  time: '2024-11-22 15:00', done: true },
    ],
  },
  {
    id: 'MNT-2024-009', vehicleId: 'V004', vehicle: 'Mahindra Blazo X 35',
    registration: 'DL-04-GH-3456', type: 'Coolant System Flush', category: 'Preventive',
    technician: 'Sunil Patil', priority: 'medium',
    startDate: '2024-11-15', expectedCompletion: '2024-11-15', completionDate: '2024-11-15',
    cost: 4800, actualCost: 4800, status: 'completed',
    odometer: 93200,
    issueDescription: 'Coolant flush and thermostat replacement at scheduled interval.',
    partsReplaced: ['Coolant (20L)', 'Thermostat', 'Radiator Cap'],
    notes: 'No issues found during inspection.',
    timeline: [
      { event: 'Scheduled',          time: '2024-11-14 16:00', done: true },
      { event: 'Inspection Started', time: '2024-11-15 08:00', done: true },
      { event: 'Repair Started',     time: '2024-11-15 08:30', done: true },
      { event: 'Parts Ordered',      time: '2024-11-15 08:30', done: true },
      { event: 'Repair Completed',   time: '2024-11-15 11:00', done: true },
      { event: 'Quality Check',      time: '2024-11-15 11:30', done: true },
      { event: 'Vehicle Available',  time: '2024-11-15 12:00', done: true },
    ],
  },
  {
    id: 'MNT-2024-010', vehicleId: 'V006', vehicle: 'Volvo FH 500',
    registration: 'GJ-06-KL-2345', type: 'Annual Safety Inspection', category: 'Inspection',
    technician: 'Rajesh Kumar', priority: 'high',
    startDate: '2024-11-10', expectedCompletion: '2024-11-11', completionDate: '2024-11-11',
    cost: 6500, actualCost: 6500, status: 'completed',
    odometer: 56200,
    issueDescription: 'Annual government-mandated safety inspection and fitness certificate renewal.',
    partsReplaced: ['Wiper Blades', 'Headlight Bulbs'],
    notes: 'Fitness certificate valid until Nov 2025.',
    timeline: [
      { event: 'Scheduled',          time: '2024-11-09 10:00', done: true },
      { event: 'Inspection Started', time: '2024-11-10 09:00', done: true },
      { event: 'Repair Started',     time: '2024-11-10 10:00', done: true },
      { event: 'Parts Ordered',      time: '2024-11-10 10:00', done: true },
      { event: 'Repair Completed',   time: '2024-11-11 12:00', done: true },
      { event: 'Quality Check',      time: '2024-11-11 13:00', done: true },
      { event: 'Vehicle Available',  time: '2024-11-11 14:00', done: true },
    ],
  },
];

export const MAINTENANCE_COST_TREND = [
  { month: 'Jul', monthly: 42000, repair: 28000, service: 14000 },
  { month: 'Aug', monthly: 58000, repair: 38000, service: 20000 },
  { month: 'Sep', monthly: 35000, repair: 20000, service: 15000 },
  { month: 'Oct', monthly: 71000, repair: 50000, service: 21000 },
  { month: 'Nov', monthly: 62000, repair: 42000, service: 20000 },
  { month: 'Dec', monthly: 89000, repair: 65000, service: 24000 },
];

export const MAINTENANCE_STATUS_DATA = [
  { name: 'Scheduled',   value: 2, color: '#3B82F6' },
  { name: 'In Progress', value: 1, color: '#F59E0B' },
  { name: 'Completed',   value: 6, color: '#22C55E' },
  { name: 'Overdue',     value: 1, color: '#EF4444' },
];

export const MAINTENANCE_KPI = {
  inShop:        { value: '3',      desc: '2 critical, 1 in progress',    trend: '+1 this week',   trendUp: false },
  scheduled:     { value: '2',      desc: 'Next: Tata Prima — Dec 15',    trend: '-1 vs last week', trendUp: true  },
  completed:     { value: '6',      desc: '4 on time, 2 early',           trend: '+3 this month',  trendUp: true  },
  overdue:       { value: '1',      desc: 'Volvo FH 500 — 4 days late',   trend: '-2 vs last month',trendUp: true  },
  totalCost:     { value: '₹1.93L', desc: 'Dec 2024 total spend',         trend: '+43% vs Nov',    trendUp: false },
  avgRepairTime: { value: '2.4d',   desc: 'Average across all services',  trend: '-0.3d improved', trendUp: true  },
};
